# Generated by Django 4.0.4 on 2022-05-20 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cm', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('nationalty', models.CharField(max_length=30)),
                ('birthday_date', models.DateField()),
                ('prestige', models.CharField(choices=[('Pr', 'Prezident'), ('V-Pr', 'Vitse-Prezident'), ('Ijro-Dir', 'Ijro-Direktori'), ('SD', 'Sport-Direktori')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='contracts',
            old_name='contract',
            new_name='contract_id',
        ),
        migrations.AddField(
            model_name='contracts',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='birthday_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='players',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='validity',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
