# Generated by Django 4.0.4 on 2022-05-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_contracts_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.players'),
        ),
    ]
