# Generated by Django 4.0.4 on 2022-05-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_contracts_contract_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='contract_id',
            new_name='contract',
        ),
    ]
