# Generated by Django 4.0.4 on 2022-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_rename_players_player_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to='media/players'),
        ),
    ]
